CREATE TABLE Cart ( 
	CartID INT NOT NULL AUTO_INCREMENT, 
	userID INT, 
	CreatedDate Date,
    Total DOUBLE(16,2),
	CONSTRAINT ShCart_userID_FK FOREIGN KEY(userID) REFRENCES users(userID), 
	CONSTRAINT ShCart_CartID_PK PRIMARY KEY (CartID) 
); 

CREATE TABLE CartItem (
	CartItemID INT NOT NULL AUTO_INCREMENT,
	BookID INT,
	Quantity INT,
	CartID INT, 
	CONSTRAINT CartItem_CartID_PK PRIMARY KEY( CartItemID ),
	CONSTRAINT CartItem_BookID_FK FOREIGN KEY(BookID) REFRENCES books(BookID),
	CONSTRAINT CartItem_CartID_FK FOREIGN KEY(CartID) REFRENCES Cart(CartID)  
);
